# Generated by Django 5.2.17 on 2026-09-04 09:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("risk_reassessment", "Risk reassessment"),
                            ("report_generation", "Report generation"),
                            ("catalog_refresh", "Catalog refresh"),
                            ("audit_batch_seal", "Audit batch seal"),
                        ],
                        max_length=32,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("priority", models.IntegerField(default=100)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("available_at", models.DateTimeField()),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("lock_expires_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, max_length=255, null=True)),
                ("claim_token", models.UUIDField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=100, null=True)),
                ("safe_error_summary", models.TextField(blank=True, null=True)),
                (
                    "error_fingerprint",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="background_jobs",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "background_jobs",
                "ordering": ("priority", "available_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["status", "available_at", "priority", "id"],
                        name="job_claim_order_idx",
                    ),
                    models.Index(
                        fields=["status", "lock_expires_at"],
                        name="job_lease_recovery_idx",
                    ),
                    models.Index(fields=["organization"], name="job_org_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("claim_token__isnull", True),
                                ("completed_at__isnull", True),
                                ("lock_expires_at__isnull", True),
                                ("locked_at__isnull", True),
                                ("locked_by__isnull", True),
                                ("status", "queued"),
                            ),
                            models.Q(
                                ("claim_token__isnull", False),
                                ("completed_at__isnull", True),
                                ("lock_expires_at__isnull", False),
                                ("locked_at__isnull", False),
                                ("locked_by__isnull", False),
                                ("status", "running"),
                            ),
                            models.Q(
                                ("claim_token__isnull", True),
                                ("completed_at__isnull", False),
                                ("lock_expires_at__isnull", True),
                                ("locked_at__isnull", True),
                                ("locked_by__isnull", True),
                                ("status__in", ("completed", "failed")),
                            ),
                            _connector="OR",
                        ),
                        name="background_job_state_consistent",
                    )
                ],
            },
        ),
    ]
