# Generated by Django 5.2.17 on 2026-09-04 09:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assessment_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("captured_at", models.DateTimeField(editable=False)),
                ("input_payload", models.JSONField(editable=False)),
                ("result_payload", models.JSONField(editable=False)),
                ("input_sha256", models.CharField(editable=False, max_length=64)),
                ("result_sha256", models.CharField(editable=False, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_snapshots",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "assessment_snapshots",
                "ordering": ("-captured_at", "assessment_id", "version"),
                "indexes": [
                    models.Index(
                        fields=["organization", "assessment_id", "version"],
                        name="assessment_org_identity_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "assessment_id", "version"),
                        name="unique_assessment_snapshot_version",
                    )
                ],
            },
        ),
    ]
