# Generated by Django 5.2.17 on 2026-09-04 07:58

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.UUIDField(blank=True, null=True)),
                ("display_name", models.CharField(max_length=255)),
                ("vendor_name", models.CharField(max_length=255)),
                ("business_owner", models.CharField(blank=True, max_length=255)),
                ("department", models.CharField(blank=True, max_length=255)),
                ("user_count", models.PositiveIntegerField(default=0)),
                ("business_purpose", models.TextField(blank=True)),
                ("monthly_cost_cents", models.PositiveIntegerField(default=0)),
                ("seat_count", models.PositiveIntegerField(default=0)),
                ("connected_systems", models.JSONField(blank=True, default=list)),
                ("data_categories", models.JSONField(blank=True, default=list)),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("capabilities", models.JSONField(blank=True, default=list)),
                (
                    "autonomy_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "It does not act on its own"),
                            (1, "It suggests actions for a person to take"),
                            (2, "It acts only after a person approves"),
                            (3, "It can perform some tasks on its own"),
                            (4, "It can perform important tasks on its own"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("human_approval", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trial", "Trial"),
                            ("inactive", "Inactive"),
                            ("reviewing", "Reviewing"),
                        ],
                        default="reviewing",
                        max_length=16,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "Entered by a person"),
                            ("csv", "Imported from a spreadsheet"),
                            ("discovered", "Discovered from a connected source"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_items",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_items",
                "ordering": ("display_name", "id"),
                "indexes": [
                    models.Index(fields=["organization"], name="inventory_org_idx"),
                    models.Index(
                        fields=["organization", "status"],
                        name="inventory_org_status_idx",
                    ),
                ],
            },
        ),
    ]
