# Generated by Django 5.2.17 on 2026-09-04 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0002_database_security"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="inventoryitem",
                    name="product_id",
                ),
                migrations.AddField(
                    model_name="inventoryitem",
                    name="product",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_items",
                        to="catalog.product",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE inventory_items ADD CONSTRAINT "
                        "inventory_items_product_fk FOREIGN KEY (product_id) "
                        "REFERENCES catalog_product (id) "
                        "DEFERRABLE INITIALLY DEFERRED; "
                        "CREATE INDEX inventory_items_product_idx "
                        "ON inventory_items (product_id);"
                    ),
                    reverse_sql=(
                        "DROP INDEX IF EXISTS inventory_items_product_idx; "
                        "ALTER TABLE inventory_items DROP CONSTRAINT IF EXISTS "
                        "inventory_items_product_fk;"
                    ),
                )
            ],
        )
    ]
