# Generated by Django 5.2.17 on 2026-09-05 02:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_remove_inventoryitem_product_id_and_more"),
        ("organizations", "0002_public_onboarding"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveryScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scan_hash", models.CharField(max_length=64)),
                ("device_id", models.UUIDField()),
                ("observed_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("bundle", models.JSONField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "discovery_scans",
            },
        ),
        migrations.CreateModel(
            name="DetectionEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("evidence_hash", models.CharField(max_length=64)),
                ("record", models.JSONField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="inventory.discoveryscan",
                    ),
                ),
            ],
            options={
                "db_table": "detection_evidence",
            },
        ),
        migrations.AddConstraint(
            model_name="discoveryscan",
            constraint=models.UniqueConstraint(
                fields=("organization", "scan_hash"), name="scan_org_hash_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="discoveryscan",
            constraint=models.UniqueConstraint(
                fields=("id", "organization"), name="scan_id_org_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="detectionevidence",
            constraint=models.UniqueConstraint(
                fields=("organization", "scan", "fingerprint"),
                name="evidence_scan_identity_unique",
            ),
        ),
    ]
