# Generated by Django 5.2.17 on 2026-09-05 03:03

import hashlib

import django.db.models.deletion
from django.db import migrations, models


def populate_legacy_discovery_fingerprints(apps, schema_editor):
    inventory_item = apps.get_model("inventory", "InventoryItem")
    for item in inventory_item.objects.filter(
        source_type="discovered",
        discovery_fingerprint="",
    ).iterator():
        material = f"legacy-discovered-inventory:{item.organization_id}:{item.id}"
        item.discovery_fingerprint = hashlib.sha256(material.encode()).hexdigest()
        item.save(update_fields=("discovery_fingerprint",))


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_catalog_security"),
        ("inventory", "0005_discovery_security"),
        ("organizations", "0002_public_onboarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionevidence",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detection_evidence",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="detectionevidence",
            name="matched_identifier_type",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="detectionevidence",
            name="matched_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detection_evidence",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="detectionevidence",
            name="reconciliation_reason",
            field=models.CharField(default="not_reconciled_at_ingest", max_length=64),
        ),
        migrations.AddField(
            model_name="detectionevidence",
            name="reconciliation_status",
            field=models.CharField(
                choices=[
                    ("reconciled", "Exact catalog match"),
                    ("review", "Review required"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="discovery_fingerprint",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=64
            ),
        ),
        migrations.RunPython(
            populate_legacy_discovery_fingerprints,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="detectionevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("inventory_item__isnull", False),
                        ("matched_product__isnull", False),
                        ("reconciliation_status", "reconciled"),
                    ),
                    models.Q(
                        ("inventory_item__isnull", True),
                        ("matched_product__isnull", True),
                        ("reconciliation_status__in", ("review", "unknown")),
                    ),
                    _connector="OR",
                ),
                name="evidence_reconciliation_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_type", "discovered")),
                fields=("organization", "discovery_fingerprint"),
                name="inventory_discovery_fingerprint_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.UniqueConstraint(
                fields=("id", "organization"), name="inventory_id_org_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_type", "discovered"),
                        models.Q(("discovery_fingerprint", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("source_type", "discovered"), _negated=True),
                        ("discovery_fingerprint", ""),
                    ),
                    _connector="OR",
                ),
                name="discovered_inventory_has_fingerprint",
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE detection_evidence ADD CONSTRAINT "
                "evidence_inventory_same_tenant FOREIGN KEY "
                "(inventory_item_id, organization_id) REFERENCES "
                "inventory_items(id, organization_id);"
            ),
            reverse_sql=(
                "ALTER TABLE detection_evidence DROP CONSTRAINT IF EXISTS "
                "evidence_inventory_same_tenant;"
            ),
        ),
    ]
