# Generated by Django 5.2.17 on 2026-09-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_detectionevidence_inventory_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="declared_fields",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
