# Generated by Django 5.2.17 on 2026-09-04 09:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("enabled", models.BooleanField(default=True)),
                ("definition", models.JSONField()),
                (
                    "result_on_match",
                    models.CharField(
                        choices=[
                            ("FAIL", "Does not meet the rule"),
                            ("WARNING", "Needs attention"),
                        ],
                        default="WARNING",
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MODERATE", "Moderate"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MODERATE",
                        max_length=16,
                    ),
                ),
                ("explanation", models.TextField()),
                ("remediation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organization_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_rules",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_rules",
                "ordering": ("name", "id"),
                "indexes": [
                    models.Index(
                        fields=["organization"], name="organization_rule_org_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "name"),
                        name="unique_organization_rule_name",
                    )
                ],
            },
        ),
    ]
