# Generated by Django 5.2.17 on 2026-09-05 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_detectionevidence_inventory_item_and_more"),
        ("organizations", "0002_public_onboarding"),
        ("policies", "0002_organization_rule_security"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="organizationrule",
            name="unique_organization_rule_name",
        ),
        migrations.AddField(
            model_name="organizationrule",
            name="detector_id",
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name="organizationrule",
            name="detector_version",
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name="organizationrule",
            name="generation_fingerprint",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=64
            ),
        ),
        migrations.AddField(
            model_name="organizationrule",
            name="mapping_id",
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name="organizationrule",
            name="mapping_version",
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name="organizationrule",
            name="source_inventory_item",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detector_rules",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="organizationrule",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Created by a person"),
                    ("detector", "Created from Collector evidence"),
                ],
                default="manual",
                editable=False,
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_type", "manual")),
                fields=("organization", "name"),
                name="unique_manual_organization_rule_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_type", "detector")),
                fields=("organization", "generation_fingerprint"),
                name="unique_detector_rule_fingerprint",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_inventory_item__isnull", False),
                        ("source_type", "detector"),
                        models.Q(("generation_fingerprint", ""), _negated=True),
                        models.Q(("detector_id", ""), _negated=True),
                        models.Q(("detector_version", ""), _negated=True),
                        models.Q(("mapping_id", ""), _negated=True),
                        models.Q(("mapping_version", ""), _negated=True),
                    ),
                    models.Q(
                        ("detector_id", ""),
                        ("detector_version", ""),
                        ("generation_fingerprint", ""),
                        ("mapping_id", ""),
                        ("mapping_version", ""),
                        ("source_inventory_item__isnull", True),
                        ("source_type", "manual"),
                    ),
                    _connector="OR",
                ),
                name="organization_rule_provenance_shape",
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE organization_rules ADD CONSTRAINT "
                "rule_inventory_same_tenant FOREIGN KEY "
                "(source_inventory_item_id, organization_id) REFERENCES "
                "inventory_items(id, organization_id);"
            ),
            reverse_sql=(
                "ALTER TABLE organization_rules DROP CONSTRAINT IF EXISTS "
                "rule_inventory_same_tenant;"
            ),
        ),
    ]
