# Generated by Django 5.2.17 on 2026-09-04 10:38

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditChainHead",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="audit_chain_head",
                        serialize=False,
                        to="organizations.organization",
                    ),
                ),
                ("last_block_sequence", models.BigIntegerField(default=0)),
                (
                    "last_block_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "audit_chain_heads",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("last_block_sequence__gte", 0)),
                        name="audit_chain_sequence_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("last_block_hash__isnull", True),
                                ("last_block_sequence", 0),
                            ),
                            models.Q(
                                ("last_block_hash__isnull", False),
                                ("last_block_sequence__gt", 0),
                            ),
                            _connector="OR",
                        ),
                        name="audit_chain_hash_matches_sequence",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditMerkleBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("block_sequence", models.BigIntegerField()),
                ("algorithm_version", models.CharField(max_length=64)),
                ("canonicalization_version", models.CharField(max_length=64)),
                ("event_count", models.PositiveIntegerField()),
                ("first_event_id", models.UUIDField()),
                ("last_event_id", models.UUIDField()),
                ("merkle_root", models.CharField(max_length=64)),
                (
                    "previous_block_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("block_hash", models.CharField(max_length=64)),
                (
                    "sealed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_merkle_blocks",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "audit_merkle_blocks",
                "ordering": ("organization_id", "block_sequence"),
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "actor_user_id",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("event_type", models.CharField(editable=False, max_length=160)),
                ("entity_type", models.CharField(editable=False, max_length=160)),
                ("entity_id", models.UUIDField(blank=True, editable=False, null=True)),
                ("data", models.JSONField(default=dict, editable=False)),
                (
                    "node_hash",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
                (
                    "batch_position",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "batch_block",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="audit.auditmerkleblock",
                    ),
                ),
            ],
            options={
                "db_table": "audit_events",
                "ordering": ("occurred_at", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="auditmerkleblock",
            index=models.Index(
                fields=["organization", "block_sequence"], name="audit_block_chain_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="auditmerkleblock",
            constraint=models.UniqueConstraint(
                fields=("organization", "block_sequence"),
                name="audit_block_org_sequence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditmerkleblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("block_sequence__gte", 1)),
                name="audit_block_sequence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditmerkleblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("event_count__gte", 1)),
                name="audit_block_event_count_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["organization", "occurred_at", "id"],
                name="audit_event_order_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["organization", "batch_block", "occurred_at", "id"],
                name="audit_unsealed_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("batch_block__isnull", True),
                        ("batch_position__isnull", True),
                        ("node_hash__isnull", True),
                    ),
                    models.Q(
                        ("batch_block__isnull", False),
                        ("batch_position__isnull", False),
                        ("node_hash__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="audit_event_seal_state_consistent",
            ),
        ),
    ]
