# Generated by Django 5.2.17 on 2026-09-04 14:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assessments", "0002_snapshot_security"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.BigIntegerField(editable=False, unique=True)),
                ("identifier_year", models.PositiveSmallIntegerField(editable=False)),
                (
                    "report_identifier",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                (
                    "organization_display_name",
                    models.CharField(editable=False, max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment_snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report",
                        to="assessments.assessmentsnapshot",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "ordering": ("-created_at", "report_identifier"),
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"],
                        name="report_org_created_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1)),
                        name="report_sequence_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("identifier_year__gte", 2000)),
                        name="report_identifier_year_supported",
                    ),
                ],
            },
        ),
    ]
