# Generated by Django 5.2.17 on 2026-09-04 17:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0002_snapshot_security"),
        ("organizations", "0001_initial"),
        ("reports", "0002_report_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "object_key",
                    models.CharField(editable=False, max_length=512, unique=True),
                ),
                (
                    "content_type",
                    models.CharField(
                        default="application/pdf", editable=False, max_length=100
                    ),
                ),
                ("sha256", models.CharField(editable=False, max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_artifacts",
                        to="assessments.assessmentsnapshot",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_artifacts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifact",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "db_table": "report_artifacts",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"],
                        name="artifact_org_created_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("size_bytes__gte", 1)),
                        name="report_artifact_size_positive",
                    )
                ],
            },
        ),
    ]
