# Generated by Django 5.2.17 on 2026-09-04 08:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("website_domain", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("unverified", "Review incomplete"),
                        ],
                        default="unverified",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("is_ai_product", models.BooleanField(default=True)),
                ("default_risk_profile", models.JSONField(blank=True, default=dict)),
                ("catalog_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ("vendor__name", "name", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProductIdentifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("microsoft_app_id", "Microsoft application ID"),
                            ("google_client_id", "Google client ID"),
                            ("oauth_client_id", "OAuth client ID"),
                            ("hostname", "Hostname"),
                            ("domain", "Domain"),
                            ("origin", "Origin"),
                            ("redirect_uri", "Redirect URI"),
                            ("product_name", "Product name"),
                        ],
                        max_length=32,
                    ),
                ),
                ("raw_value", models.CharField(max_length=1024)),
                ("canonical_value", models.CharField(editable=False, max_length=1024)),
                (
                    "normalization_version",
                    models.CharField(default="AL-ID-1", editable=False, max_length=16),
                ),
                (
                    "provider_scope",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ("identifier_type", "canonical_value", "id"),
                "indexes": [
                    models.Index(
                        fields=["identifier_type", "canonical_value", "provider_scope"],
                        name="catalog_identifier_lookup_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("identifier_type", "canonical_value", "provider_scope"),
                        name="unique_catalog_identifier",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("vendor", "name", "catalog_version"),
                name="unique_catalog_product_version",
            ),
        ),
    ]
