# Generated by Django 5.2.17 on 2026-09-04 08:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reviewing", "Needs review"),
                            ("ready", "Ready for final approval"),
                            ("imported", "Imported"),
                        ],
                        default="reviewing",
                        max_length=16,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_import_batches",
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("data", models.JSONField(default=dict)),
                ("errors", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="imports.importbatch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_rows",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_import_rows",
                "ordering": ("row_number", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(fields=["organization"], name="import_batch_org_idx"),
        ),
        migrations.AddIndex(
            model_name="importrow",
            index=models.Index(fields=["organization"], name="import_row_org_idx"),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "row_number"), name="unique_import_batch_row"
            ),
        ),
    ]
